### ISSUE TITLE
a node cannot start with empty keyring

### ISSUE THREAD

**Issue by jmastr** [planetmint/planetmint-go#465]
we have read-only (non-validator) nodes in the network and they cannot start if the keyring is empty (which might be a valid case)?!
```
Nov 11 13:09:47 vm-planetmint-testnet planetmint-god[1860638]: panic: runtime error: index out of range [0] with length 0
Nov 11 13:09:47 vm-planetmint-testnet planetmint-god[1860638]: goroutine 34 [running]:
Nov 11 13:09:47 vm-planetmint-testnet planetmint-god[1860638]: github.com/planetmint/planetmint-go/lib.(*Config).GetDefaultValidatorRecord(0x25d0dac?)
Nov 11 13:09:47 vm-planetmint-testnet planetmint-god[1860638]:         /home/runner/work/planetmint-go/planetmint-go/lib/config.go:150 +0xbf
Nov 11 13:09:47 vm-planetmint-testnet planetmint-god[1860638]: github.com/planetmint/planetmint-go/config.(*Config).GetValidatorAddress(0xc0010f02c0?)
Nov 11 13:09:47 vm-planetmint-testnet planetmint-god[1860638]:         /home/runner/work/planetmint-go/planetmint-go/config/config.go:94 +0x4e
Nov 11 13:09:47 vm-planetmint-testnet planetmint-god[1860638]: github.com/planetmint/planetmint-go/monitor.getClientID()
Nov 11 13:09:47 vm-planetmint-testnet planetmint-god[1860638]:         /home/runner/work/planetmint-go/planetmint-go/monitor/mqtt_monitor.go:71 +0x18
Nov 11 13:09:47 vm-planetmint-testnet planetmint-god[1860638]: github.com/planetmint/planetmint-go/monitor.(*MqttMonitor).lazyLoadMonitorMQTTClient(0xc0010a2240)
Nov 11 13:09:47 vm-planetmint-testnet planetmint-god[1860638]:         /home/runner/work/planetmint-go/planetmint-go/monitor/mqtt_monitor.go:87 +0x2e5
Nov 11 13:09:47 vm-planetmint-testnet planetmint-god[1860638]: github.com/planetmint/planetmint-go/monitor.(*MqttMonitor).MonitorActiveParticipants(0xc0010a2240)
Nov 11 13:09:47 vm-planetmint-testnet planetmint-god[1860638]:         /home/runner/work/planetmint-go/planetmint-go/monitor/mqtt_monitor.go:315 +0x127
Nov 11 13:09:47 vm-planetmint-testnet planetmint-god[1860638]: created by github.com/planetmint/planetmint-go/monitor.(*MqttMonitor).Start in goroutine 15
Nov 11 13:09:47 vm-planetmint-testnet planetmint-god[1860638]:         /home/runner/work/planetmint-go/planetmint-go/monitor/mqtt_monitor.go:129 +0xc5
Nov 11 13:09:47 vm-planetmint-testnet systemd[1]: planetmint-go.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

**Comment by GR3G0RYO** [comment]
Identify Non Validators in some way.

Should ppl be able to run non validator nodes?
- Make requirement to have a key in the key ring
- Or have a TW to connect


Verify requirement that validator has either a TW or a key ring and if not it must be taken down
